#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# MeshSat Bridge — Docker Compose Installer
# Usage: curl -fsSL https://get.meshsat.net | sudo bash
#
# Installs MeshSat Bridge as a Docker Compose service.
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

MESHSAT_INSTALLER_VERSION="1.1.0"
MESHSAT_IMAGE="ghcr.io/cubeos-app/meshsat:latest"
MESHSAT_PORT="${MESHSAT_PORT:-6050}"
MESHSAT_DIR="/meshsat"
COMPOSE_CMD=""

# ─── Output helpers ───────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

log_info()    { printf "${BLUE}[INFO]${NC}  %s\n" "$*"; }
log_ok()      { printf "${GREEN}[OK]${NC}    %s\n" "$*"; }
log_warn()    { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
log_error()   { printf "${RED}[ERROR]${NC} %s\n" "$*" >&2; }
log_fatal()   { log_error "$@"; exit 1; }
log_step()    { printf "\n${BOLD}── %s${NC}\n" "$*"; }

# ═══════════════════════════════════════════════════════════════════════════════
# Pre-flight checks
# ═══════════════════════════════════════════════════════════════════════════════

preflight_root() {
    if [ "$(id -u)" -ne 0 ]; then
        log_fatal "Run with sudo: curl -fsSL https://get.meshsat.net | sudo bash"
    fi
    log_ok "Running as root"
}

preflight_arch() {
    local arch
    arch=$(uname -m)
    case "$arch" in
        x86_64|amd64)   log_ok "Architecture: x86_64" ;;
        aarch64|arm64)   log_ok "Architecture: aarch64" ;;
        *)               log_fatal "Unsupported architecture: $arch (need x86_64 or aarch64)" ;;
    esac
}

preflight_docker() {
    if ! command -v docker &>/dev/null; then
        log_info "Docker not found — installing via get.docker.com..."
        curl -fsSL https://get.docker.com | sh
        systemctl enable --now docker
        log_ok "Docker installed"
    else
        log_ok "Docker found: $(docker --version)"
    fi

    # Detect compose command: docker compose (v2 plugin) or docker-compose (v1 standalone)
    if docker compose version &>/dev/null 2>&1; then
        COMPOSE_CMD="docker compose"
        log_ok "Compose found: $($COMPOSE_CMD version --short 2>/dev/null || echo 'v2 plugin')"
    elif command -v docker-compose &>/dev/null; then
        COMPOSE_CMD="docker-compose"
        log_ok "Compose found: $(docker-compose --version 2>/dev/null)"
    else
        log_info "Docker Compose not found — installing plugin..."
        apt-get update -qq && apt-get install -y -qq docker-compose-plugin 2>/dev/null \
            || yum install -y docker-compose-plugin 2>/dev/null \
            || dnf install -y docker-compose-plugin 2>/dev/null \
            || log_fatal "Could not install Docker Compose. Install manually: https://docs.docker.com/compose/install/"
        COMPOSE_CMD="docker compose"
        log_ok "Docker Compose plugin installed"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# Installation
# ═══════════════════════════════════════════════════════════════════════════════

create_directories() {
    log_step "Creating directory structure"
    mkdir -p "${MESHSAT_DIR}/data"
    log_ok "Created ${MESHSAT_DIR}/data"
}

generate_compose() {
    log_step "Generating docker-compose.yml"

    cat > "${MESHSAT_DIR}/docker-compose.yml" <<COMPOSE
# MeshSat Bridge — Docker Compose (standalone mode)
# Generated by MeshSat installer v${MESHSAT_INSTALLER_VERSION}
# https://meshsat.net

services:
  meshsat:
    image: ${MESHSAT_IMAGE}
    container_name: meshsat
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - MESHSAT_MODE=direct
      - MESHSAT_PORT=${MESHSAT_PORT}
      - MESHSAT_DB_PATH=/data/meshsat.db
    volumes:
      - meshsat-data:/data
      - /dev:/dev
      - /sys:/sys:ro

volumes:
  meshsat-data:
COMPOSE

    log_ok "Generated ${MESHSAT_DIR}/docker-compose.yml"
}

pull_and_start() {
    log_step "Pulling and starting MeshSat Bridge"

    cd "${MESHSAT_DIR}"
    $COMPOSE_CMD pull
    log_ok "Image pulled"

    $COMPOSE_CMD up -d
    log_ok "MeshSat Bridge started"
}

print_success() {
    local ip
    ip=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

    printf "\n"
    printf "${GREEN}═══════════════════════════════════════════════════════════════${NC}\n"
    printf "${GREEN}  MeshSat Bridge installed successfully!${NC}\n"
    printf "${GREEN}═══════════════════════════════════════════════════════════════${NC}\n"
    printf "\n"
    printf "  Dashboard:  ${BOLD}http://%s:%s${NC}\n" "$ip" "$MESHSAT_PORT"
    printf "  Data dir:   %s/data\n" "$MESHSAT_DIR"
    printf "  Logs:       cd %s && %s logs -f\n" "$MESHSAT_DIR" "$COMPOSE_CMD"
    printf "\n"
    printf "  To stop:    cd %s && %s down\n" "$MESHSAT_DIR" "$COMPOSE_CMD"
    printf "  To update:  cd %s && %s pull && %s up -d\n" "$MESHSAT_DIR" "$COMPOSE_CMD" "$COMPOSE_CMD"
    printf "\n"
    printf "  USB devices will be auto-detected.\n"
    printf "  Plug in your Meshtastic radio or satellite modem.\n"
    printf "\n"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

main() {
    printf "\n${BOLD}MeshSat Bridge Installer v%s${NC}\n" "$MESHSAT_INSTALLER_VERSION"
    printf "https://meshsat.net\n\n"

    preflight_root
    preflight_arch
    preflight_docker
    create_directories
    generate_compose
    pull_and_start
    print_success
}

main "$@"
