#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# MeshSat Bridge — Docker Compose Installer
# Usage: curl -fsSL https://get.meshsat.net | sudo bash
#
# Installs MeshSat Bridge as a Docker Compose service.
# ═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

MESHSAT_INSTALLER_VERSION="1.0.0"
MESHSAT_IMAGE="ghcr.io/cubeos-app/meshsat:latest"
MESHSAT_PORT="${MESHSAT_PORT:-6050}"
MESHSAT_DIR="/meshsat"

# ─── Output helpers ───────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

log_info()    { printf "${BLUE}[INFO]${NC}  %s\n" "$*"; }
log_ok()      { printf "${GREEN}[OK]${NC}    %s\n" "$*"; }
log_warn()    { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
log_error()   { printf "${RED}[ERROR]${NC} %s\n" "$*" >&2; }
log_fatal()   { log_error "$@"; exit 1; }
log_step()    { printf "\n${BOLD}── %s${NC}\n" "$*"; }

# ═══════════════════════════════════════════════════════════════════════════════
# Pre-flight checks
# ═══════════════════════════════════════════════════════════════════════════════

preflight_root() {
    if [ "$(id -u)" -ne 0 ]; then
        log_fatal "Run with sudo: curl -fsSL https://get.meshsat.net | sudo bash"
    fi
    log_ok "Running as root"
}

preflight_docker() {
    if ! command -v docker &>/dev/null; then
        log_fatal "Docker is not installed. Install Docker first: https://docs.docker.com/engine/install/"
    fi
    log_ok "Docker found: $(docker --version)"

    if ! docker compose version &>/dev/null; then
        log_fatal "Docker Compose plugin is not installed. Install it: https://docs.docker.com/compose/install/"
    fi
    log_ok "Docker Compose found: $(docker compose version --short)"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Installation
# ═══════════════════════════════════════════════════════════════════════════════

create_directories() {
    log_step "Creating directory structure"
    mkdir -p "${MESHSAT_DIR}/data"
    log_ok "Created ${MESHSAT_DIR}/data"
}

generate_compose() {
    log_step "Generating docker-compose.yml"

    cat > "${MESHSAT_DIR}/docker-compose.yml" <<COMPOSE
# MeshSat Bridge — Docker Compose
# Generated by MeshSat installer v${MESHSAT_INSTALLER_VERSION}
# https://meshsat.net

services:
  meshsat:
    image: ${MESHSAT_IMAGE}
    container_name: meshsat
    restart: unless-stopped
    ports:
      - "${MESHSAT_PORT}:6050"
    volumes:
      - ${MESHSAT_DIR}/data:/meshsat/data
    environment:
      - MESHSAT_DATA_DIR=/meshsat/data
COMPOSE

    log_ok "Generated ${MESHSAT_DIR}/docker-compose.yml"
}

pull_and_start() {
    log_step "Pulling and starting MeshSat Bridge"

    cd "${MESHSAT_DIR}"
    docker compose pull
    log_ok "Image pulled"

    docker compose up -d
    log_ok "MeshSat Bridge started"
}

print_success() {
    local ip
    ip=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

    printf "\n"
    printf "${GREEN}═══════════════════════════════════════════════════════════════${NC}\n"
    printf "${GREEN}  MeshSat Bridge installed successfully!${NC}\n"
    printf "${GREEN}═══════════════════════════════════════════════════════════════${NC}\n"
    printf "\n"
    printf "  Dashboard:  ${BOLD}http://%s:%s${NC}\n" "$ip" "$MESHSAT_PORT"
    printf "  Data dir:   %s/data\n" "$MESHSAT_DIR"
    printf "  Logs:       docker compose -f %s/docker-compose.yml logs -f\n" "$MESHSAT_DIR"
    printf "\n"
    printf "  To stop:    docker compose -f %s/docker-compose.yml down\n" "$MESHSAT_DIR"
    printf "  To update:  docker compose -f %s/docker-compose.yml pull && \\ \n" "$MESHSAT_DIR"
    printf "              docker compose -f %s/docker-compose.yml up -d\n" "$MESHSAT_DIR"
    printf "\n"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

main() {
    printf "\n${BOLD}MeshSat Bridge Installer v%s${NC}\n" "$MESHSAT_INSTALLER_VERSION"
    printf "https://meshsat.net\n\n"

    preflight_root
    preflight_docker
    create_directories
    generate_compose
    pull_and_start
    print_success
}

main "$@"
